SELECT ID_INSTANCE_INFO,INSTANCE_NAME FROM REPORTDBA.INSTANCE_INFO WHERE INSTANCE_NAME='';
SELECT ID_RESPONSABLE_INFO,NOMBRE,APELLIDO_P,APELLIDO_M FROM REPORTDBA.RESPONSABLE_INFO;

SPOOL /tmp/insert_tablespace_resp.sql
SELECT 'INSERT INTO REPORTDBA.TABLESPACE_INFO (ID_TABLESPACE_INFO,ID_TABLESPACE_INFO_DETALLE,ID_RESPONSABLE_INFO) 
VALUES (REPORTDBA.TABLESPACE_INFO_SEQ.NEXTVAL,'
	||ID_TABLESPACE_INFO_DETALLE 	||','
	||ID_RESPONSABLE_INFO  	        ||');' 
FROM REPORTDBA.TABLESPACE_INFO_DETALLE  TID,
	 REPORTDBA.RESPONSABLE_INFO RI
WHERE 
TID.ID_INSTANCE_INFO IN
( 
  SELECT ID_INSTANCE_INFO FROM REPORTDBA.INSTANCE_INFO WHERE INSTANCE_NAME='OPERAP'
)
AND 
RI.ID_RESPONSABLE_INFO IN
(
  SELECT ID_RESPONSABLE_INFO FROM REPORTDBA.RESPONSABLE_INFO WHERE NOMBRE='Maria' AND APELLIDO_P='Almaguer'
);
spool off

@/tmp/insert_tablespace_resp.sql

-- SELECCIONAR RELACION TABLESPACE-RESPONSABLE
SELECT TID.TABLESPACE_NAME,TID.TABLESPACE_NAME,RI.NOMBRE,RI.APELLIDO_P,RI.APELLIDO_M 
FROM REPORTDBA.TABLESPACE_INFO 			TSI,
	 REPORTDBA.TABLESPACE_INFO_DETALLE  TID,
	 REPORTDBA.RESPONSABLE_INFO 		RI
WHERE TSI.ID_TABLESPACE_INFO_DETALLE=TID.ID_TABLESPACE_INFO_DETALLE
AND   RI.ID_RESPONSABLE_INFO=TSI.ID_RESPONSABLE_INFO;