-- CONSULTAS PARA

-- ELIMINAR INSTANCIAS QUE NO EXISTEN EN LA TABLA DE INSTANCIAS
SET LINE 300 PAGES 999 ECHO OFF FEED OFF
SPOOL /TMP/DELETE_INSTANCIAS_MAL.SQL
SELECT 'DELETE REPORTDBA.TABLESPACES_DB WHERE INSTANCIA=''' ||INSTANCIA||''';' 
FROM 
(
	SELECT DISTINCT INSTANCIA FROM REPORTDBA.TABLESPACES_DB
	WHERE
	INSTANCIA IN  
	(
		SELECT DISTINCT INSTANCIA FROM REPORTDBA.TABLESPACES_DB
		WHERE 
		INSTANCIA NOT IN 
		(
			SELECT INSTANCE_NAME FROM 
			(
				SELECT II.INSTANCE_NAME 
				FROM   REPORTDBA.TABLESPACE_INFO_DETALLE TID,REPORTDBA.INSTANCE_INFO II 
				WHERE  TID.ID_INSTANCE_INFO=II.ID_INSTANCE_INFO
			)
		)
	)
);
SPOOL OFF

SET LINE 300 PAGES 999 ECHO ON FEED ON
@/TMP/DELETE_INSTANCIAS_MAL.SQL

--------------------------------------------------------------------------------------------------------------------------------------
-- OBTENER INSTANCIA DE TS-SEGMENTOS
SELECT DISTINCT INSTANCIA FROM REPORTDBA.TABLESPACES_DB WHERE INSTANCIA='SMP';
SELECT DISTINCT INSTANCIA FROM REPORTDBA.TABLESPACES_DB WHERE INSTANCIA='SMP';		

---------------------------------------------------------------------------------------------------------------------------------------
-- UPDATE INSTANCIAS
UPDATE REPORTDBA.INSTANCE_INFO SET INSTANCE_NAME='SAPDQPRO' WHERE INSTANCE_NAME='SAPDQPRO';
UPDATE REPORTDBA.INSTANCE_INFO SET INSTANCE_NAME='SMP' WHERE INSTANCE_NAME='SMPIXE';

---------------------------------------------------------------------------------------------------------------------------------------
-- SELECCCIONAR RELACION DBA-INSTANCIA
SELECT II.INSTANCE_NAME,DAID.NOMBRE||' '||DAID.APELLIDO_P
FROM   REPORTDBA.DBA_ADMIN_INFO DAI, REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID, REPORTDBA.INSTANCE_INFO II
WHERE  DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
AND    DAI.ID_INSTANCE_INFO   =II.ID_INSTANCE_INFO;

-- SELECCCIONAR RELACION DBA-INSTANCIA (JOIN)
SELECT  II.INSTANCE_NAME
        ||'|'||DAID.NOMBRE
        ||' '||DAID.APELLIDO_P
FROM   
REPORTDBA.INSTANCE_INFO II 
JOIN
REPORTDBA.DBA_ADMIN_INFO DAI ON DAI.ID_INSTANCE_INFO= II.ID_INSTANCE_INFO
JOIN
REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID  ON DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
ORDER BY 1;

-- OBTENER BASES DE DBA
SELECT II.INSTANCE_NAME,DAID.NOMBRE||' '||DAID.APELLIDO_P
FROM   REPORTDBA.DBA_ADMIN_INFO DAI, REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID, REPORTDBA.INSTANCE_INFO II
WHERE  DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
AND    DAI.ID_INSTANCE_INFO   =II.ID_INSTANCE_INFO
AND    DAID.NOMBRE='CARLOS ABRAHAM';

-- TODOS LOS DBA'S
SELECT DISTINCT DAID.NOMBRE
FROM   REPORTDBA.DBA_ADMIN_INFO DAI, REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID, REPORTDBA.INSTANCE_INFO II
WHERE  DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
AND    DAI.ID_INSTANCE_INFO   =II.ID_INSTANCE_INFO;
---------------------------------------------------------------------------------------------------------------------------------------
-- TABLESPACES REPORTE SIN DBA
SELECT  TO_DATE(TD.FECHA,'DD/MM/YYYY')
        ||'|'||TD.HOST_NAME
        ||'|'||TD.INSTANCIA
        ||'|'||TD.TABLESPACE_NAME
        ||'|'||TD.TAMANO_MB
        ||'|'||TD.UTILIZADOS_MB
        ||'|'||TD.LIBRES_MB
        ||'|'||TD.PERCENT_USED
FROM   
REPORTDBA.TABLESPACES_DB TD 
WHERE
                                TD.PERCENT_USED>89
                            AND TD.TABLESPACE_NAME NOT LIKE 'UNDO%'
                            AND TD.TABLESPACE_NAME NOT LIKE 'PSAPUNDO%'
                            AND TRUNC(TD.FECHA)=TRUNC(SYSDATE)
ORDER BY 1;

-- REPORTE TABLESPACE-INSTANCIA-DBA (SUB CONSULTA)
 ALTER SESSION SET NLS_DATE_FORMAT = 'DDMMYYYY';

 SELECT  TO_DATE(TD.FECHA,'DD/MM/YYYY')||'|'||TD.HOST_NAME||'|'||TD.INSTANCIA||'|'||TD.TABLESPACE_NAME||'|'||TD.TAMANO_MB||'|'||TD.UTILIZADOS_MB||'|'||TD.LIBRES_MB||'|'||TD.PERCENT_USED||'|'||JJ.NOMBRE||' '||JJ.APELLIDO_P
 FROM REPORTDBA.TABLESPACES_DB TD, 
    (
    	      SELECT II.INSTANCE_NAME,DAID.NOMBRE,DAID.APELLIDO_P
                FROM   REPORTDBA.DBA_ADMIN_INFO DAI, REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID, REPORTDBA.INSTANCE_INFO II
                WHERE  DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
                AND    DAI.ID_INSTANCE_INFO   =II.ID_INSTANCE_INFO
    ) JJ
 WHERE
 JJ.INSTANCE_NAME=TD.INSTANCIA
 AND TD.PERCENT_USED>89
 AND TD.TABLESPACE_NAME NOT LIKE 'UNDO%'
 AND TD.TABLESPACE_NAME NOT LIKE 'PSAPUNDO%'
 AND TRUNC(TD.FECHA)=TRUNC(SYSDATE)
 ORDER BY 1;

------------------------------------------------------------------------------------------------------------------------------------
-- REPORTE UNION CON DBA (JOIN)
SELECT TO_DATE(TD.FECHA,'DD/MM/YYYY')
        ||'|'||TD.HOST_NAME
        ||'|'||TD.INSTANCIA
        ||'|'||TD.TABLESPACE_NAME
        ||'|'||TD.TAMANO_MB
        ||'|'||TD.UTILIZADOS_MB
        ||'|'||TD.LIBRES_MB
        ||'|'||TD.PERCENT_USED
        ||'|'||NVL(II.NOMBRE,'FALTA REGISTRAR')
        ||' '||NVL(II.APELLIDO_P,'')
FROM   
REPORTDBA.TABLESPACES_DB TD 
LEFT JOIN
(
	SELECT  II.INSTANCE_NAME,DAID.NOMBRE,DAID.APELLIDO_P 
	FROM 
	REPORTDBA.INSTANCE_INFO II  
	JOIN
	REPORTDBA.DBA_ADMIN_INFO DAI ON DAI.ID_INSTANCE_INFO= II.ID_INSTANCE_INFO
	JOIN
	REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID  ON DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
) II
  ON  TD.INSTANCIA = II.INSTANCE_NAME
  WHERE TD.PERCENT_USED>89
  AND TD.TABLESPACE_NAME NOT LIKE 'UNDO%'
  AND TD.TABLESPACE_NAME NOT LIKE 'PSAPUNDO%'
  AND TRUNC(TD.FECHA)=TRUNC(SYSDATE)
ORDER BY 1;

**********************************************************************************************************************************
-- REPORTE UNION CON DBA (JOIN)
SELECT TO_DATE(TD.FECHA,'DD/MM/YYYY')
        ||'|'||TD.HOST_NAME
        ||'|'||TD.INSTANCIA
        ||'|'||TD.TABLESPACE_NAME
        ||'|'||TD.TAMANO_MB
        ||'|'||TD.UTILIZADOS_MB
        ||'|'||TD.LIBRES_MB
        ||'|'||TD.PERCENT_USED
        ||'|'||NVL(II.NOMBRE,'FALTA REGISTRAR')
        ||' '||NVL(II.APELLIDO_P,'')
        ||'|'||NVL(TID.NOMBRE,'SIN RESPONSABLE')
        ||' '||NVL(TID.APELLIDO_P,'')
FROM   
REPORTDBA.TABLESPACES_DB TD 
LEFT JOIN
(
	SELECT  II.INSTANCE_NAME,DAID.NOMBRE,DAID.APELLIDO_P 
	FROM 
	REPORTDBA.INSTANCE_INFO II  
	JOIN
	REPORTDBA.DBA_ADMIN_INFO DAI ON DAI.ID_INSTANCE_INFO= II.ID_INSTANCE_INFO
	JOIN
	REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID  ON DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
) II
  ON  TD.INSTANCIA = II.INSTANCE_NAME
LEFT JOIN 
(
	SELECT 	TID.TABLESPACE_NAME,RI.NOMBRE,RI.APELLIDO_P,RI.APELLIDO_M 
	FROM 	REPORTDBA.TABLESPACE_INFO 			TSI 
	JOIN
	REPORTDBA.TABLESPACE_INFO_DETALLE  	TID 	ON  TID.ID_TABLESPACE_INFO_DETALLE=TSI.ID_TABLESPACE_INFO_DETALLE
	JOIN  		
	REPORTDBA.RESPONSABLE_INFO 			RI      ON  RI.ID_RESPONSABLE_INFO=TSI.ID_RESPONSABLE_INFO
) TID
  ON TID.TABLESPACE_NAME=TD.TABLESPACE_NAME
  WHERE TD.PERCENT_USED>89
  AND TD.TABLESPACE_NAME NOT LIKE 'UNDO%'
  AND TD.TABLESPACE_NAME NOT LIKE 'PSAPUNDO%'
  AND TRUNC(TD.FECHA)=TRUNC(SYSDATE)
ORDER BY 1;
**************************************************************************************************************
-- OBTENER TABLESPACE-RESPONSABLE


