                SET PAGESIZE 0;
                SET FEED OFF;
                SET HEAD OFF;
                SET ECHO OFF;
                SET LINESIZE 1000;
                SET VERIFY OFF;

                COL INSTANCE_NAME   FORMAT A15
                COL HOST_NAME       FORMAT A12
                COL TABLESPACE_NAME FORMAT A50
                COL TAMANO     FORMAT 9999999.99
                COL UTILIZADOS FORMAT 9999999.99
                COL LIBRES     FORMAT 9999999.99
                COL PERCENT_USED FORMAT 999.99

ALTER SESSION SET NLS_DATE_FORMAT = 'DDMMYYYY';
 SELECT  to_date(td.FECHA,'DD/MM/YYYY')||'|'||td.HOST_NAME||'|'||td.INSTANCIA||'|'||td.TABLESPACE_NAME||'|'||td.TAMANO_MB||'|'||td.UTILIZADOS_MB||'|'||td.LIBRES_MB||'|'||td.PERCENT_USED||'|'||jj.nombre||' '||jj.APELLIDO_P
 from reportdba.TABLESPACES_DB td, 
    (SELECT II.INSTANCE_NAME,DAID.NOMBRE,DAID.APELLIDO_P
                FROM   REPORTDBA.DBA_ADMIN_INFO DAI, REPORTDBA.DBA_ADMIN_INFO_DETALLE DAID, REPORTDBA.INSTANCE_INFO II
                WHERE  DAI.ID_DBA_INFO_DETALLE=DAID.ID_DBA_ADMIN_INFO_DETALLE
                AND    DAI.ID_INSTANCE_INFO   =II.ID_INSTANCE_INFO
    ) jj 
 where
 jj.INSTANCE_NAME=td.INSTANCIA
 and td.PERCENT_USED>89
 and td.TABLESPACE_NAME NOT LIKE 'UNDO%'
 and td.TABLESPACE_NAME NOT LIKE 'PSAPUNDO%'
 and trunc(td.FECHA)=trunc(SYSDATE)
 ORDER BY 1;

SELECT TRUNC(SYSDATE, 'DD') "'DD'" FROM DUAL;
SELECT SYSDATE FROM DUAL;